name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  mlops:
    name: Train + Build + Push Image + Deploy
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: file:./mlruns
      PYTHONPATH: .

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Python setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      # 4️⃣ Pull DVC 
      - name: Pull DVC data
        continue-on-error: true
        run: dvc pull || echo "No DVC remote - using local."

      # 5️⃣ Preprocess data
      - name: Data preprocessing
        run: |
          python mlops_src/data_preprocess.py \
            --input data/raw/flight_price.csv \
            --out_dir data/processed

      # 6️⃣ Feature pipeline
      - name: Build feature pipeline
        run: |
          python mlops_src/feature_pipeline.py \
            --data data/processed/train_data.csv \
            --artifacts backend_artifacts

      # 7️⃣ Train model
      - name: Train XGBoost
        run: python mlops_src/train.py

      # 8️⃣ Copy artifacts → docker backend
      - name: Update backend artifacts
        run: python mlops_src/update_artifacts.py

      # 9️⃣ Build & push Docker image
      - name: Build & Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t aeroprice-backend ./docker_backend
          docker tag aeroprice-backend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/aeroprice-backend:latest
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/aeroprice-backend:latest

#  🔥 NEW STEP — automatic deployment trigger for Render
# ---- 🔟 Deploy to Render (auto-trigger deploy) ----
      - name: Deploy to Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_TOKEN" \
          -H "accept: application/json" \
          -H "content-type: application/json" \
          -d '{"image": "'"${{ secrets.DOCKERHUB_USERNAME }}"'/aeroprice-backend:latest"}' \
          https://api.render.com/deploy/srv-d53s9pmmcj7s73ee2u5g?key=c2JWLl9fgj8 